services:
  # وب سرویس اصلی برنامه
  - type: web
    name: linkresan
    env: go
    goVersion: "1.25.0" # <--- نسخه دقیق Go را اینجا مشخص می‌کنیم
    branch: main
    buildCommand: "go build -o linkresan-app ./main.go"
    startCommand: "./linkresan-app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linkresan-db
          property: connectionString

databases:
  # پایگاه داده پروژه
  - name: linkresan-db
    databaseName: linkresan_db
    user: postgres
    plan: free