services:
  - type: web
    name: linkresan
    env: go
    goVersion: "1.25.0"
    branch: main
    buildCommand: "go build -o ./linkresan-app ./main.go"
    startCommand: "./linkresan-app"
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linkresan-db
          property: connectionString

databases:
  - name: linkresan-db
    databaseName: linkresan_db
    user: postgres
    plan: free